<a href="https://colab.research.google.com/github/yuna778/DALC_Scala/blob/main/numpystudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DALC_Scala: numpy기초


## 1. 빅데이터 분석 및 처리
1) 프로그래밍 언어
- 빅데이터의 정의
  * 관계형 데이터베이스 관리 시스템과 같은 전통적 데이터 관리 기법으로 다루기 힘든 데이터
- R
  * 통계 계산과 그래픽을 위한 프로그래밍 언어이자 소프트웨어 환경
  * 다양한 통계 기법과 수치 해석기법 지원
- python
  * 단순한 문법 구조를 가진 고수준의 언어
  * 이해하기 쉽고 유연한 문법
  * 연산능력을 극대화 시켜주는 오픈소스 라이브러리(모듈)가 풍부함

2) 파이썬 프로그래밍 도구 기반 빅데이터 분석 및 처리과정 탐구
- 활용 이유
  * 대용량 데이터 세트의 분석과 처리에 유연성 가짐
  * 다양한 패키지가 목적에 맞게 개발됨
  * 꾸준히 개발 및 출시가 진행됨
  
        * 예)
        - Numpy: 동일한 데이터 타입을 가진 배열 기반의 데이터 처리
        - Pandas: data frame 형태로 데이터를 다룸
        - Scipy: 과학 계산 작업
        - Matplotlib: 데이터 시각화
        - Scikit-Learn: 머신러닝
    


## 2. 데이터 저장 및 가공
1) 데이터 분석
- 데이터
  * 이미지, 사운드 등 다양한 형식으로 존재
  * 컴퓨터 내부 연산 처리 → 숫자 배열로 변환

        * 예)
          - 이미지 데이터 → 픽셀 밝기를 나타내는 2차원 숫자 배열
          - 사운드 데이터 → 시간 대비 강도를 나타내는 1차원 배열차원 숫자 배열
                    - 사운드 데이터 → 시간 대비 강도를 나타내는 1차원 배열


          1. 원본 데이터를 숫자 배열로 변환
          2. 편한 방식으로 연산 적용
          3. 연산 결과를 다루기 쉬운 형태로 변환
          4. 분석        


  * 숫자 배열을 효율적으로 __저장하고 가공하는 것__ 은 데이터 분석을 위한 기본 절차
  ㅁ
  * 숫자 배열을 전문적으로 다루는 __Numpy 패키지__ 필요


## 3. Numpy 패키지
1) 넘파이(Numerical Python)
- 개요
  * 벡터 및 행렬 연산에 유용한 기능 제공
  * 빅데이터 분석을 위해 사용되는 라이브러리<br>pandad와 matplotlib에서 기본으로 사용되는 패키지

- 특징
  * __array__ 단위로 데이터 관리 및 연산 수행용되는 패키지
  > array: 동일한 데이터 타입을 갖는 벡터나 행렬
  * 배열 규모가 커질수록 데이터 저장 및 처리에 효율적
      
## 4. 행렬 생성
1) 넘파이 패키지 임포트




In [11]:
import numpy as np

2) array 정의와 사용 방법
- data 1, data 2 리스트 생성

In [12]:
data1 = [1,2,3,4,5]
data2 = [6,5,4,3,2,1]
print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


- ar1 numpy 배열 생성

In [13]:
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

- ar2 numpy 배열 생성

In [14]:
ar2 = np.array(data1, dtype='float32')
ar2

array([1., 2., 3., 4., 5.], dtype=float32)

3) 다차원 배열 구성
- 다차원 배열 초기화화

In [20]:
ar3 = np.array([range(i, i + 3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

- full 함수

In [21]:
ar4 = np.full((3, 5), 3.14)
ar4

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

- arange 함수

In [22]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

4) 배열 구성
- linspace 함수

In [23]:
ar6 = np.linspace(0, 1, 3)
ar6

array([0. , 0.5, 1. ])

5) 무작위 값의 배열 구성
- random 함수

In [24]:
ar7 = np.random.random((3,3))
ar7

array([[0.06569346, 0.64053856, 0.3021795 ],
       [0.37641167, 0.52367488, 0.58624387],
       [0.98986573, 0.97022195, 0.62377574]])

- randint 함수

In [29]:
ar8 = np.random.randint(0, 100, (3, 3))
ar8

array([[31, 84, 64],
       [47, 31, 71],
       [24,  2, 15]])

6) 단위 행렬 생성
- eye 함수

In [30]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5. Numpy 표준 데이터 타입
- Numpy의 배열은 한가지 데이터 타입값만을 담고 있음
- 데이터 타입의 종류와 제약 사항을 살펴보는 것이 numpy의 활용 측면에서 매우 중요

## 6. 배열 분할, 재구성, 결합
1) 배열 속성


In [33]:
import numpy as np
x = np.random.randint(10, size=(3, 4, 5))
x

print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)

x ndim: 3
x shape: (3, 4, 5)
x size: 60


  * ndim: 차원의 개수
  * shape: 각 차원의 크기
  * size: 전체 배열의 크기기

In [34]:
y=np.array([2, 4, 6, 8, 10])
print(y[0], y[-2])

2 8


> 개별 배열요소 값을 가져오거나 특정 위치에 값을 설정하기 위해 사용

<br>

3) 다차원 배열 인덱싱

In [35]:
z=np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]])
print(z[1, 0])

3


In [36]:
z[0, 0]=12
z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

4) 배열 슬라이싱
- 콜론(:) 기호를 나타내는 슬라이스(slice) 표기법
> x[start:stop:step]
  
  * 기본값
    - start는 0으로 설정
    - stop은 차원 크기로 설정
    - step은 1로 설정
   

In [37]:
x=np.arange(10)
x[4:8]

array([4, 5, 6, 7])

In [38]:
x=np.arange(10)
x[:5]

# 첫번째 다섯 요소를 가진 하위 배열 생성

array([0, 1, 2, 3, 4])

In [39]:
x=np.arange(10)
x[5:]

# 인덱스 5 이후의 요소를 가진 하위 배열을 생성성

array([5, 6, 7, 8, 9])

5) 다차원 배열 슬라이싱
- 콤마(,)로 구분된 다중 슬라이스(slice) 표기법

In [40]:
z=np.array([[2, 4, 6, 8], [3, 6, 9, 12], [4, 8, 12, 16]])
z[:2, :3]

array([[2, 4, 6],
       [3, 6, 9]])

> 인덱스 0,1행과 인덱스 0,1,2 열로 구성되는 다차원 하위 배열 생성

In [41]:
z=np.array([[2, 4, 6, 8], [3, 6, 9, 12], [4, 8, 12, 16]])
z[:3, :2]

array([[2, 4],
       [3, 6],
       [4, 8]])

> 모든 행마다 한 열씩 걸러 구성된 다차원 하위 배열 생성

In [42]:
z=np.arange(1, 10).reshape(3, 3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> 배열의 형상을 변경

<br>

7) 배열 결합
- concatenate, vstack, hstatrck

In [43]:
x=np.array([1, 2, 3])
y=np.array([3, 2, 1])
z=np.concatenate([x,y])
z

array([1, 2, 3, 3, 2, 1])

  * vstack: 수직스택
  *  hstatrck: 수평스택

In [45]:
x=np.array([1, 2, 3])
grid=np.array([[4, 5, 6], [7, 8, 9]])
v=np.vstack([x, grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

8) 배열 분할
- split, vsplit, hsplit

In [47]:
x= [1, 2, 3, 77, 77, 3, 2, 1]
x1, x2, x3 = np.split(x,[3, 5])
print(x1, x2, x3)

[1 2 3] [77 77] [3 2 1]


In [48]:
grid = np.arange(16).reshape((4, 4))
upper, lower=np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [49]:
grid = np.arange(16).reshape((4, 4))
left, right=np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


> grid 배열이 좌우 2개로 나뉨뉨